# Generated by Django 4.2 on 2024-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapi', '0004_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
